#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/etaico/.vscode-server/bin/19e0f9e681ecb8e5c09d8784acaa601316ca4571/node" "/home/etaico/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"